baseURL = "http://dalton.games/"
languageCode = "en-us"
title = "Shane Dalton"
theme = "dream"
defaultContentLanguage = "en"

[params]
	#background = "black"
	linkcolor = "seagreen"
	email = "shane@dalton.games"
	linkedin = "shanedaltondesign"
	avatar = "/img/avatar.png"
	itch = "shanemakesgames"