baseURL = "http://affectionate-williams-254cf4.netlify.com/"
languageCode = "en-us"
title = "Shane Dalton"
theme = "dream"
defaultContentLanguage = "en"

[params]
	#background = "black"
	linkcolor = "seagreen"
	email = "shane@dalton.games"
	linkedin = "shanedaltondesign"